version: '3'
services:
  backend:
    build: akenord-backend
    ports:
      - 8080:8080
    environment:
        - spring.datasource.url=jdbc:mysql://mysql:3306/akenord?enabledTLSProtocols=TLSv1.2
        - spring.datasource.username=root # MySQL root username
        - spring.datasource.password=Akenord123456 # MySQL root password
    depends_on:
      - mysql

  frontend:
    build: akenordV2
    ports:
      - 3000:3000

  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: akenord
      MYSQL_ROOT_PASSWORD: Akenord123456
      command: --innodb-flush-method=O_DIRECT --innodb-use-native-aio=ON # Optional MySQL configuration for performance

networks:
  springapimysql-net:
