FROM node:14

# Set the working directory to /app inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (if present) to the container
COPY akenordV2/package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY akenordV2 .

# Expose port 3000 for the React app
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
